In [29]:
import numpy as np
import pandas as pd

import pickle

In [25]:
df = pd.read_csv('/home/ubuntu/csvs/codes_to_use.csv')

In [26]:
df

,Unnamed: 0,code,name,description,refreshed_at,from_date,to_date
0,1072,A038RC1,"Compensation of Employees, Received: Supplemen...",Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:14,1959-01-01 00:00:00,2019-01-01 00:00:00
1,1080,A041RC1,Proprietors' income with inventory valuation a...,Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:10,1959-01-01 00:00:00,2019-01-01 00:00:00
2,1085,A045RC1,Proprietors' income with inventory valuation a...,Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:08,1959-01-01 00:00:00,2019-01-01 00:00:00
3,1088,A048RC1,Rental income of persons with capital consumpt...,Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:07,1959-01-01 00:00:00,2019-01-01 00:00:00
4,1117,A061RC1,"Contributions for government social insurance,...",Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:07,1959-01-01 00:00:00,2019-01-01 00:00:00
5,1123,A063RC1,Personal current transfer receipts: Government...,Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:05,1959-01-01 00:00:00,2019-01-01 00:00:00
6,1320,A132RC1,"Compensation of Employees, Received: Wage and ...",Billions of Dollars Seasonally Adjusted Annual...,2019-03-03 04:28:11,1959-01-01 00:00:00,2019-01-01 00:00:00
7,1701,A229RC0,Disposable Personal Income: Per capita: Curren...,"Dollars Seasonally Adjusted Annual Rate,",2019-03-03 04:28:12,1959-01-01 00:00:00,2019-01-01 00:00:00
8,1870,A31SNO,Value of Manufacturers' New Orders for Durable...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:48,1992-02-01 00:00:00,2019-01-01 00:00:00
9,1871,A31STI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:32,1992-01-01 00:00:00,2019-01-01 00:00:00
10,1872,A31SUO,Value of Manufacturers' Unfilled Orders for Du...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:33,1992-01-01 00:00:00,2019-01-01 00:00:00
11,1874,A31SVS,Value of Manufacturers' Shipments for Durable ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:34,1992-01-01 00:00:00,2019-01-01 00:00:00
12,1927,A32SNO,Value of Manufacturers' New Orders for Durable...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:47,1992-02-01 00:00:00,2019-01-01 00:00:00
13,1928,A32STI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:32,1992-01-01 00:00:00,2019-01-01 00:00:00
14,1929,A32SUO,Value of Manufacturers' Unfilled Orders for Du...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:33,1992-01-01 00:00:00,2019-01-01 00:00:00
15,1931,A32SVS,Value of Manufacturers' Shipments for Durable ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:31,1992-01-01 00:00:00,2019-01-01 00:00:00
16,2010,A33SNO,Value of Manufacturers' New Orders for Durable...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:47,1992-02-01 00:00:00,2019-01-01 00:00:00
17,2011,A33STI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:34,1992-01-01 00:00:00,2019-01-01 00:00:00
18,2012,A33SUO,Value of Manufacturers' Unfilled Orders for Du...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:32,1992-01-01 00:00:00,2019-01-01 00:00:00
19,2014,A33SVS,Value of Manufacturers' Shipments for Durable ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:31,1992-01-01 00:00:00,2019-01-01 00:00:00
20,2097,A34SNO,Value of Manufacturers' New Orders for Durable...,"Million of Dollars Seasonally Adjusted, Data o...",2019-03-14 01:26:47,1992-02-01 00:00:00,2019-01-01 00:00:00
21,2098,A34STI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:33,1992-01-01 00:00:00,2019-01-01 00:00:00
22,2099,A34SUO,Value of Manufacturers' Unfilled Orders for Du...,"Million of Dollars Seasonally Adjusted, Data o...",2019-03-14 01:26:33,1992-01-01 00:00:00,2019-01-01 00:00:00
23,2101,A34SVS,Value of Manufacturers' Shipments for Durable ...,"Million of Dollars Seasonally Adjusted, Estima...",2019-03-14 01:26:48,1992-01-01 00:00:00,2019-01-01 00:00:00
24,2103,A34XNO,Value of Manufacturers' New Orders for Communi...,"Million of Dollars Seasonally Adjusted, This s...",2019-03-14 01:26:31,1992-02-01 00:00:00,2019-01-01 00:00:00
25,2104,A34XTI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted, This s...",2019-03-14 01:26:32,1992-01-01 00:00:00,2019-01-01 00:00:00
26,2105,A34XUO,Value of Manufacturers' Unfilled Orders for Co...,"Million of Dollars Seasonally Adjusted, This s...",2019-03-14 01:26:32,1992-01-01 00:00:00,2019-01-01 00:00:00
27,2106,A34XVS,Value of Manufacturers' Shipments for Communic...,"Million of Dollars Seasonally Adjusted, This s...",2019-03-14 01:26:31,1992-01-01 00:00:00,2019-01-01 00:00:00
28,2178,A35SNO,Value of Manufacturers' New Orders for Durable...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:47,1992-02-01 00:00:00,2019-01-01 00:00:00
29,2179,A35STI,Value of Manufacturers' Total Inventories for ...,"Million of Dollars Seasonally Adjusted,",2019-03-14 01:26:36,1992-01-01 00:00:00,2019-01-01 00:00:00
...,...,...,...,...,...,...,...
28749,336748,WYSUBL5URN,"Unemployment Rate in Sublette County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:35:08,1990-01-01 00:00:00,2019-01-01 00:00:00
28750,336756,WYSWEE7LFN,"Civilian Labor Force in Sweetwater County, WY","Thousands of Persons Not Seasonally Adjusted,",2019-03-16 01:35:17,1990-01-01 00:00:00,2019-01-01 00:00:00
28751,336758,WYSWEE7URN,"Unemployment Rate in Sweetwater County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:34:51,1990-01-01 00:00:00,2019-01-01 00:00:00
28752,336766,WYTETO9LFN,"Civilian Labor Force in Teton County, WY","Thousands of Persons Not Seasonally Adjusted,",2019-03-16 01:35:28,1990-01-01 00:00:00,2019-01-01 00:00:00
28753,336768,WYTETO9URN,"Unemployment Rate in Teton County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:35:08,1990-01-01 00:00:00,2019-01-01 00:00:00
28754,336815,WYUINT1LFN,"Civilian Labor Force in Uinta County, WY","Thousands of Persons Not Seasonally Adjusted,",2019-03-16 01:35:18,1990-01-01 00:00:00,2019-01-01 00:00:00
28755,336817,WYUINT1URN,"Unemployment Rate in Uinta County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:35:22,1990-01-01 00:00:00,2019-01-01 00:00:00
28756,336840,WYWASH3LFN,"Civilian Labor Force in Washakie County, WY","Thousands of Persons Not Seasonally Adjusted,",2019-03-16 01:31:33,1990-01-01 00:00:00,2019-01-01 00:00:00
28757,336842,WYWASH3URN,"Unemployment Rate in Washakie County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:35:18,1990-01-01 00:00:00,2019-01-01 00:00:00
28758,336852,WYWEST5LFN,"Civilian Labor Force in Weston County, WY","Thousands of Persons Not Seasonally Adjusted,",2019-03-16 01:31:33,1990-01-01 00:00:00,2019-01-01 00:00:00
28759,336854,WYWEST5URN,"Unemployment Rate in Weston County, WY","Percent Not Seasonally Adjusted,",2019-03-16 01:31:33,1990-01-01 00:00:00,2019-01-01 00:00:00
28760,339449,YAKI453LF,"Civilian Labor Force in Yakima, WA (MSA)","Persons Smoothed Seasonally Adjusted,",2019-03-16 01:29:55,1990-01-01 00:00:00,2019-01-01 00:00:00
28761,339450,YAKI453LFN,"Civilian Labor Force in Yakima, WA (MSA)","Persons Not Seasonally Adjusted,",2019-03-16 01:34:51,1990-01-01 00:00:00,2019-01-01 00:00:00
28762,339462,YAKI453UR,"Unemployment Rate in Yakima, WA (MSA)","Percent Smoothed Seasonally Adjusted,",2019-03-16 01:30:28,1990-01-01 00:00:00,2019-01-01 00:00:00
28763,339463,YAKI453URN,"Unemployment Rate in Yakima, WA (MSA)","Percent Not Seasonally Adjusted,",2019-03-16 01:46:33,1990-01-01 00:00:00,2019-01-01 00:00:00
28764,339474,YORK642LF,"Civilian Labor Force in York-Hanover, PA (MSA)","Persons Smoothed Seasonally Adjusted,",2019-03-16 01:29:31,1990-01-01 00:00:00,2019-01-01 00:00:00
28765,339475,YORK642LFN,"Civilian Labor Force in York-Hanover, PA (MSA)","Persons Not Seasonally Adjusted,",2019-03-16 01:36:38,1990-01-01 00:00:00,2019-01-01 00:00:00
28766,339489,YORK642UR,"Unemployment Rate in York-Hanover, PA (MSA)","Percent Smoothed Seasonally Adjusted,",2019-03-16 01:30:28,1990-01-01 00:00:00,2019-01-01 00:00:00
28767,339490,YORK642URN,"Unemployment Rate in York-Hanover, PA (MSA)","Percent Not Seasonally Adjusted,",2019-03-16 01:36:36,1990-01-01 00:00:00,2019-01-01 00:00:00
28768,339501,YOUN639LF,Civilian Labor Force in Youngstown-Warren-Boar...,"Persons Smoothed Seasonally Adjusted,",2019-03-16 01:29:58,1990-01-01 00:00:00,2019-01-01 00:00:00
28769,339502,YOUN639LFN,Civilian Labor Force in Youngstown-Warren-Boar...,"Persons Not Seasonally Adjusted,",2019-03-16 01:47:09,1990-01-01 00:00:00,2019-01-01 00:00:00
28770,339516,YOUN639UR,Unemployment Rate in Youngstown-Warren-Boardma...,"Percent Smoothed Seasonally Adjusted,",2019-03-16 01:30:39,1990-01-01 00:00:00,2019-01-01 00:00:00
28771,339517,YOUN639URN,Unemployment Rate in Youngstown-Warren-Boardma...,"Percent Not Seasonally Adjusted,",2019-03-16 01:47:25,1990-01-01 00:00:00,2019-01-01 00:00:00
28772,339528,YUBA706LF,"Civilian Labor Force in Yuba City, CA (MSA)","Persons Smoothed Seasonally Adjusted,",2019-03-16 01:29:55,1990-01-01 00:00:00,2019-01-01 00:00:00
28773,339529,YUBA706LFN,"Civilian Labor Force in Yuba City, CA (MSA)","Persons Not Seasonally Adjusted,",2019-03-16 01:33:09,1990-01-01 00:00:00,2019-01-01 00:00:00
28774,339543,YUBA706UR,"Unemployment Rate in Yuba City, CA (MSA)","Percent Smoothed Seasonally Adjusted,",2019-03-16 01:30:28,1990-01-01 00:00:00,2019-01-01 00:00:00
28775,339544,YUBA706URN,"Unemployment Rate in Yuba City, CA (MSA)","Percent Not Seasonally Adjusted,",2019-03-16 01:42:51,1990-01-01 00:00:00,2019-01-01 00:00:00
28776,339555,YUMA704LF,"Civilian Labor Force in Yuma, AZ (MSA)","Persons Smoothed Seasonally Adjusted,",2019-03-16 01:29:54,1990-01-01 00:00:00,2019-01-01 00:00:00
28777,339556,YUMA704LFN,"Civilian Labor Force in Yuma, AZ (MSA)","Persons Not Seasonally Adjusted,",2019-03-16 01:31:37,1990-01-01 00:00:00,2019-01-01 00:00:00
28778,339570,YUMA704UR,"Unemployment Rate in Yuma, AZ (MSA)","Percent Smoothed Seasonally Adjusted,",2019-03-16 01:30:28,1990-01-01 00:00:00,2019-01-01 00:00:00

In [27]:
codes = df['code'].tolist()

In [41]:
len(codes)

28779

In [40]:
with open('/home/ubuntu/notebooks/codes.pickle', 'wb') as p:
    pickle.dump(codes, p)