In [14]:
import numpy as np
import pandas as pd

from fbprophet import Prophet

In [25]:
etfs = pd.read_csv('etfs_pivot.csv')
etfs['date'] = pd.to_datetime(etfs['date'])

In [16]:
first_year = pd.date_range(start = '2014-03-17', end = '2015-03-16').tolist()
second_year = pd.date_range(start = '2015-03-17', end = '2016-03-15').tolist()
third_year = pd.date_range(start = '2016-03-17', end = '2017-03-16').tolist()
fourth_year = pd.date_range(start = '2017-03-17', end = '2018-03-16').tolist()
fifth_year = pd.date_range(start = '2018-03-17', end = '2019-03-15').tolist()

In [26]:
spy = etfs[['date','SPY']]

In [27]:
spy_fourth = spy[spy['date'].isin(pd.date_range(first_year[0], fourth_year[-1]))]
spy_fourth.columns = ['ds', 'y']

In [28]:
arima = Prophet()
arima.fit(spy_fourth)
future = arima.make_future_dataframe(periods = len(fifth_year))
forecast = arima.predict(future)

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):

In [29]:
forecast_fifth = forecast[forecast['ds'].isin(fifth_year)]['yhat']

In [30]:
forecast_fifth

1461    272.179606
1462    272.109619
1463    272.120636
1464    272.083129
1465    272.198327
1466    272.100972
1467    272.109403
1468    272.013109
1469    271.903918
1470    271.885765
1471    271.829459
1472    271.936432
1473    271.841494
1474    271.862902
1475    271.789917
1476    271.713979
1477    271.738486
1478    271.733551
1479    271.899766
1480    271.870961
1481    271.964283
1482    271.967769
1483    271.971541
1484    272.077602
1485    272.154618
1486    272.401707
1487    272.451227
1488    272.618881
1489    272.691325
1490    272.757385
           ...
1795    312.048193
1796    312.300073
1797    312.459763
1798    312.616468
1799    312.871381
1800    313.092471
1801    313.478286
1802    313.660741
1803    313.955233
1804    314.148234
1805    314.328514
1806    314.596950
1807    314.821327
1808    315.200130
1809    315.365336
1810    315.632516
1811    315.788434
1812    315.922252
1813    316.135338
1814    316.296059
1815    316.603563
1816    316.690564
1817    316.873436
1818    316.939804
1819    316.979737
1820    317.095557
1821    317.156614
1822    317.363066
1823    317.348653
1824    317.430787
Name: yhat, Length: 364, dtype: float64

In [31]:
spy_fifth = spy[spy['date'].isin(fifth_year)]

In [32]:
spy_predict = pd.DataFrame(index = spy_fifth['date'])
spy_predict['actual'] = np.array(spy_fifth['SPY'])
spy_predict['forecast'] = np.array(forecast_fifth)
spy_predict['residual'] = spy_predict['actual'] - spy_predict['forecast']

In [33]:
spy_predict

              actual    forecast   residual
date
2018-03-17  268.9819  272.179606  -3.197706
2018-03-18  268.9819  272.109619  -3.127719
2018-03-19  265.3425  272.120636  -6.778136
2018-03-20  265.7937  272.083129  -6.289429
2018-03-21  265.2836  272.198327  -6.914727
2018-03-22  258.6523  272.100972 -13.448672
2018-03-23  253.1392  272.109403 -18.970203
2018-03-24  253.1392  272.013109 -18.873909
2018-03-25  253.1392  271.903918 -18.764718
2018-03-26  260.0649  271.885765 -11.820865
2018-03-27  255.6407  271.829459 -16.188759
2018-03-28  254.8853  271.936432 -17.051132
2018-03-29  258.1422  271.841494 -13.699294
2018-03-30  258.1422  271.862902 -13.720702
2018-03-31  258.1422  271.789917 -13.647717
2018-04-01  258.1422  271.713979 -13.571779
2018-04-02  252.5703  271.738486 -19.168186
2018-04-03  255.8075  271.733551 -15.926051
2018-04-04  258.5444  271.899766 -13.355366
2018-04-05  260.5848  271.870961 -11.286161
2018-04-06  254.7774  271.964283 -17.186883
2018-04-07  254.7774  271.967769 -17.190369
2018-04-08  254.7774  271.971541 -17.194141
2018-04-09  256.0331  272.077602 -16.044502
2018-04-10  260.1041  272.154618 -12.050518
2018-04-11  258.7406  272.401707 -13.661107
2018-04-12  260.8693  272.451227 -11.581927
2018-04-13  260.1041  272.618881 -12.514781
2018-04-14  260.1041  272.691325 -12.587225
2018-04-15  260.1041  272.757385 -12.653285
...              ...         ...        ...
2019-02-14  273.1766  312.048193 -38.871593
2019-02-15  276.1535  312.300073 -36.146573
2019-02-16  276.1535  312.459763 -36.306263
2019-02-17  276.1535  312.616468 -36.462968
2019-02-18  276.1535  312.871381 -36.717881
2019-02-19  276.6313  313.092471 -36.461171
2019-02-20  277.1889  313.478286 -36.289386
2019-02-21  276.2032  313.660741 -37.457541
2019-02-22  277.9157  313.955233 -36.039533
2019-02-23  277.9157  314.148234 -36.232534
2019-02-24  277.9157  314.328514 -36.412814
2019-02-25  278.2940  314.596950 -36.302950
2019-02-26  278.0949  314.821327 -36.726427
2019-02-27  277.9754  315.200130 -37.224730
2019-02-28  277.4577  315.365336 -37.907636
2019-03-01  279.1901  315.632516 -36.442416
2019-03-02  279.1901  315.788434 -36.598334
2019-03-03  279.1901  315.922252 -36.732152
2019-03-04  278.1746  316.135338 -37.960738
2019-03-05  277.7962  316.296059 -38.499859
2019-03-06  276.1136  316.603563 -40.489963
2019-03-07  273.8038  316.690564 -42.886764
2019-03-08  273.2562  316.873436 -43.617236
2019-03-09  273.2562  316.939804 -43.683604
2019-03-10  273.2562  316.979737 -43.723537
2019-03-11  277.2188  317.095557 -39.876757
2019-03-12  278.2642  317.156614 -38.892414
2019-03-13  280.1060  317.363066 -37.257066
2019-03-14  279.9268  317.348653 -37.421853
2019-03-15  281.3100  317.430787 -36.120787

[364 rows x 3 columns]