In [1]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine

In [2]:
engine = create_engine('postgresql://ubuntu:project-kojak@18.188.49.181:5432/roboadvisor')

In [3]:
query = '''SELECT prices.*, dividends.dividend FROM prices 
LEFT JOIN dividends ON prices.ticker = dividends.ticker AND prices.date = dividends.date;'''

prices = pd.read_sql(query, engine, index_col = 'ticker')

In [4]:
prices['date_split'] = [str(date).split() for date in prices['date']]
prices['date'] = [date[0] for date in prices['date_split']]
prices['date'] = pd.to_datetime(prices['date'])

prices = prices.drop(['adjusted_close','date_split'], axis=1)

prices = prices.fillna(0.0)
prices['split'] = 1.0

In [5]:
tickers = prices.index

tickers = sorted(list(tickers))

tickers_set = set(tickers)
tickers_list = list(tickers_set)
tickers = [str(ticker) for ticker in tickers_list]

tickers = sorted(tickers)

In [6]:
prices = prices.drop_duplicates()

prices = prices.reset_index()
prices = prices[['ticker','date','open','high','low','close','volume','dividend','split']]

prices = prices.set_index('ticker')

prices = prices.sort_values(['ticker','date'])

In [7]:
prices

,date,open,high,low,close,volume,dividend,split
ticker,,,,,,,,
AAAU,2018-08-15,11.840000,11.840000,11.740000,11.740000,27300,0.000,1.0
AAAU,2018-08-16,11.780000,11.800000,11.740000,11.740000,428400,0.000,1.0
AAAU,2018-08-17,11.800000,11.820000,11.770000,11.820000,52400,0.000,1.0
AAAU,2018-08-20,11.880000,11.910000,11.850000,11.900000,28700,0.000,1.0
AAAU,2018-08-21,11.920000,11.950000,11.890000,11.930000,30600,0.000,1.0
AAAU,2018-08-22,11.980000,11.980000,11.940000,11.960000,101200,0.000,1.0
AAAU,2018-08-23,11.910000,11.920000,11.850000,11.850000,54800,0.000,1.0
AAAU,2018-08-24,11.970000,12.080000,11.960000,12.050000,106500,0.000,1.0
AAAU,2018-08-27,12.060000,12.130000,12.060000,12.100000,295100,0.000,1.0
AAAU,2018-08-28,12.130000,12.130000,12.010000,12.010000,30400,0.000,1.0
AAAU,2018-08-29,12.060000,12.060000,12.030000,12.050000,31800,0.000,1.0
AAAU,2018-08-30,12.030000,12.030000,11.970000,12.010000,804500,0.000,1.0
AAAU,2018-08-31,12.040000,12.050000,11.990000,12.000000,39500,0.000,1.0
AAAU,2018-09-04,11.910000,11.940000,11.900000,11.920000,6000,0.000,1.0
AAAU,2018-09-05,11.980000,11.980000,11.960000,11.970000,1032800,0.000,1.0
AAAU,2018-09-06,12.070000,12.070000,11.980000,12.000000,22900,0.000,1.0
AAAU,2018-09-07,11.970000,11.980000,11.940000,11.960000,20500,0.000,1.0
AAAU,2018-09-10,11.970000,11.970000,11.940000,11.950000,64300,0.000,1.0
AAAU,2018-09-11,11.900000,11.960000,11.880000,11.960000,6800,0.000,1.0
AAAU,2018-09-12,12.030000,12.070000,12.020000,12.070000,1600,0.000,1.0
AAAU,2018-09-13,12.120000,12.120000,12.010000,12.010000,5900,0.000,1.0
AAAU,2018-09-14,12.010000,12.010000,11.930000,11.930000,13700,0.000,1.0
AAAU,2018-09-17,12.010000,12.040000,12.000000,12.010000,2214000,0.000,1.0
AAAU,2018-09-18,12.030000,12.030000,11.980000,11.980000,1000,0.000,1.0
AAAU,2018-09-19,12.040000,12.040000,12.030000,12.030000,17400,0.000,1.0
AAAU,2018-09-20,12.060000,12.070000,12.040000,12.060000,8300,0.000,1.0
AAAU,2018-09-21,12.000000,12.000000,11.970000,11.990000,3000,1.323,1.0
AAAU,2018-09-24,12.010000,12.030000,12.000000,12.000000,31500,0.000,1.0
AAAU,2018-09-25,12.020000,12.020000,12.010000,12.010000,551600,0.000,1.0
AAAU,2018-09-26,11.960000,11.990000,11.910000,11.950000,166500,0.000,1.0
...,...,...,...,...,...,...,...,...
ZSL,2019-01-29,35.689999,35.689999,35.430000,35.630001,8400,0.000,1.0
ZSL,2019-01-30,35.259998,35.480000,34.470001,34.630001,251800,0.000,1.0
ZSL,2019-01-31,34.119999,34.779999,34.049999,34.660000,20300,0.000,1.0
ZSL,2019-02-01,34.689999,35.320000,34.599998,35.209999,150300,0.000,1.0
ZSL,2019-02-04,35.689999,35.750000,35.320000,35.439999,10300,0.000,1.0
ZSL,2019-02-05,35.520000,35.669998,35.500000,35.520000,6800,0.000,1.0
ZSL,2019-02-06,35.700001,36.459999,35.700001,36.380001,7100,0.000,1.0
ZSL,2019-02-07,36.419998,36.419998,36.070000,36.099998,16300,0.000,1.0
ZSL,2019-02-08,36.000000,36.130001,35.680000,35.700001,16900,0.000,1.0
ZSL,2019-02-11,36.230000,36.419998,36.000000,36.250000,8900,0.000,1.0
ZSL,2019-02-12,36.189999,36.459999,36.189999,36.290001,10200,0.000,1.0
ZSL,2019-02-13,36.279999,37.080002,35.900002,37.070000,9800,0.000,1.0
ZSL,2019-02-14,37.189999,37.270000,36.730000,36.820000,4700,0.000,1.0
ZSL,2019-02-15,36.490002,36.799999,35.889999,35.919998,30400,0.000,1.0
ZSL,2019-02-19,35.740002,35.740002,34.930000,34.980000,14200,0.000,1.0
ZSL,2019-02-20,34.650002,34.799999,34.009998,34.610001,13400,0.000,1.0
ZSL,2019-02-21,35.220001,35.770000,35.189999,35.770000,10200,0.000,1.0
ZSL,2019-02-22,35.400002,35.430000,35.130001,35.279999,15600,0.000,1.0
ZSL,2019-02-25,35.160000,35.599998,35.160000,35.450001,38700,0.000,1.0
ZSL,2019-02-26,35.480000,35.759998,35.299999,35.299999,8200,0.000,1.0
ZSL,2019-02-27,35.709999,36.299999,35.709999,36.209999,17500,0.000,1.0
ZSL,2019-02-28,36.259998,36.930000,36.259998,36.779999,26200,0.000,1.0
ZSL,2019-03-01,37.590000,39.110001,37.360001,39.110001,75300,0.000,1.0
ZSL,2019-03-04,39.299999,39.470001,39.279999,39.380001,14900,0.000,1.0
ZSL,2019-03-05,39.369999,39.560001,39.110001,39.150002,8300,0.000,1.0
ZSL,2019-03-06,39.410000,39.549999,39.360001,39.419998,4400,0.000,1.0
ZSL,2019-03-07,40.000000,40.070000,39.610001,39.779999,11900,0.000,1.0
ZSL,2019-03-08,38.410000,38.549999,37.930000,38.000000,22500,0.000,1.0
ZSL,2019-03-11,38.230000,38.520000,38.200001,38.240002,6200,0.000,1.0
ZSL,2019-03-12,37.610001,37.840000,37.597198,37.685001,6326,0.000,1.0

In [10]:
len(prices)

2878317

In [11]:
ticker_dfs = []

for ticker in tickers:
    ticker_frame = prices[prices.index == ticker]
    ticker_frame.to_csv('/home/ubuntu/csvs/{}.csv'.format(ticker), index=False)

In [12]:
prices

,date,open,high,low,close,volume,dividend,split
ticker,,,,,,,,
AAAU,2018-08-15,11.840000,11.840000,11.740000,11.740000,27300,0.000,1.0
AAAU,2018-08-16,11.780000,11.800000,11.740000,11.740000,428400,0.000,1.0
AAAU,2018-08-17,11.800000,11.820000,11.770000,11.820000,52400,0.000,1.0
AAAU,2018-08-20,11.880000,11.910000,11.850000,11.900000,28700,0.000,1.0
AAAU,2018-08-21,11.920000,11.950000,11.890000,11.930000,30600,0.000,1.0
AAAU,2018-08-22,11.980000,11.980000,11.940000,11.960000,101200,0.000,1.0
AAAU,2018-08-23,11.910000,11.920000,11.850000,11.850000,54800,0.000,1.0
AAAU,2018-08-24,11.970000,12.080000,11.960000,12.050000,106500,0.000,1.0
AAAU,2018-08-27,12.060000,12.130000,12.060000,12.100000,295100,0.000,1.0
AAAU,2018-08-28,12.130000,12.130000,12.010000,12.010000,30400,0.000,1.0
AAAU,2018-08-29,12.060000,12.060000,12.030000,12.050000,31800,0.000,1.0
AAAU,2018-08-30,12.030000,12.030000,11.970000,12.010000,804500,0.000,1.0
AAAU,2018-08-31,12.040000,12.050000,11.990000,12.000000,39500,0.000,1.0
AAAU,2018-09-04,11.910000,11.940000,11.900000,11.920000,6000,0.000,1.0
AAAU,2018-09-05,11.980000,11.980000,11.960000,11.970000,1032800,0.000,1.0
AAAU,2018-09-06,12.070000,12.070000,11.980000,12.000000,22900,0.000,1.0
AAAU,2018-09-07,11.970000,11.980000,11.940000,11.960000,20500,0.000,1.0
AAAU,2018-09-10,11.970000,11.970000,11.940000,11.950000,64300,0.000,1.0
AAAU,2018-09-11,11.900000,11.960000,11.880000,11.960000,6800,0.000,1.0
AAAU,2018-09-12,12.030000,12.070000,12.020000,12.070000,1600,0.000,1.0
AAAU,2018-09-13,12.120000,12.120000,12.010000,12.010000,5900,0.000,1.0
AAAU,2018-09-14,12.010000,12.010000,11.930000,11.930000,13700,0.000,1.0
AAAU,2018-09-17,12.010000,12.040000,12.000000,12.010000,2214000,0.000,1.0
AAAU,2018-09-18,12.030000,12.030000,11.980000,11.980000,1000,0.000,1.0
AAAU,2018-09-19,12.040000,12.040000,12.030000,12.030000,17400,0.000,1.0
AAAU,2018-09-20,12.060000,12.070000,12.040000,12.060000,8300,0.000,1.0
AAAU,2018-09-21,12.000000,12.000000,11.970000,11.990000,3000,1.323,1.0
AAAU,2018-09-24,12.010000,12.030000,12.000000,12.000000,31500,0.000,1.0
AAAU,2018-09-25,12.020000,12.020000,12.010000,12.010000,551600,0.000,1.0
AAAU,2018-09-26,11.960000,11.990000,11.910000,11.950000,166500,0.000,1.0
...,...,...,...,...,...,...,...,...
ZSL,2019-01-29,35.689999,35.689999,35.430000,35.630001,8400,0.000,1.0
ZSL,2019-01-30,35.259998,35.480000,34.470001,34.630001,251800,0.000,1.0
ZSL,2019-01-31,34.119999,34.779999,34.049999,34.660000,20300,0.000,1.0
ZSL,2019-02-01,34.689999,35.320000,34.599998,35.209999,150300,0.000,1.0
ZSL,2019-02-04,35.689999,35.750000,35.320000,35.439999,10300,0.000,1.0
ZSL,2019-02-05,35.520000,35.669998,35.500000,35.520000,6800,0.000,1.0
ZSL,2019-02-06,35.700001,36.459999,35.700001,36.380001,7100,0.000,1.0
ZSL,2019-02-07,36.419998,36.419998,36.070000,36.099998,16300,0.000,1.0
ZSL,2019-02-08,36.000000,36.130001,35.680000,35.700001,16900,0.000,1.0
ZSL,2019-02-11,36.230000,36.419998,36.000000,36.250000,8900,0.000,1.0
ZSL,2019-02-12,36.189999,36.459999,36.189999,36.290001,10200,0.000,1.0
ZSL,2019-02-13,36.279999,37.080002,35.900002,37.070000,9800,0.000,1.0
ZSL,2019-02-14,37.189999,37.270000,36.730000,36.820000,4700,0.000,1.0
ZSL,2019-02-15,36.490002,36.799999,35.889999,35.919998,30400,0.000,1.0
ZSL,2019-02-19,35.740002,35.740002,34.930000,34.980000,14200,0.000,1.0
ZSL,2019-02-20,34.650002,34.799999,34.009998,34.610001,13400,0.000,1.0
ZSL,2019-02-21,35.220001,35.770000,35.189999,35.770000,10200,0.000,1.0
ZSL,2019-02-22,35.400002,35.430000,35.130001,35.279999,15600,0.000,1.0
ZSL,2019-02-25,35.160000,35.599998,35.160000,35.450001,38700,0.000,1.0
ZSL,2019-02-26,35.480000,35.759998,35.299999,35.299999,8200,0.000,1.0
ZSL,2019-02-27,35.709999,36.299999,35.709999,36.209999,17500,0.000,1.0
ZSL,2019-02-28,36.259998,36.930000,36.259998,36.779999,26200,0.000,1.0
ZSL,2019-03-01,37.590000,39.110001,37.360001,39.110001,75300,0.000,1.0
ZSL,2019-03-04,39.299999,39.470001,39.279999,39.380001,14900,0.000,1.0
ZSL,2019-03-05,39.369999,39.560001,39.110001,39.150002,8300,0.000,1.0
ZSL,2019-03-06,39.410000,39.549999,39.360001,39.419998,4400,0.000,1.0
ZSL,2019-03-07,40.000000,40.070000,39.610001,39.779999,11900,0.000,1.0
ZSL,2019-03-08,38.410000,38.549999,37.930000,38.000000,22500,0.000,1.0
ZSL,2019-03-11,38.230000,38.520000,38.200001,38.240002,6200,0.000,1.0
ZSL,2019-03-12,37.610001,37.840000,37.597198,37.685001,6326,0.000,1.0

In [17]:
dates = prices.date.unique()

In [19]:
dates = sorted(dates)

In [23]:
dates[0]

numpy.datetime64('2010-01-04T00:00:00.000000000')