In [1]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine

In [2]:
engine = create_engine('postgres://ubuntu:project-kojak@localhost:5432/roboadvisor')

In [109]:
query = '''SELECT prices.*, dividends.dividend FROM prices 
LEFT JOIN dividends ON prices.ticker = dividends.ticker AND prices.date = dividends.date;
'''

prices = pd.read_sql(query, engine, index_col = 'ticker')

In [110]:
prices['date_split'] = [str(date).split() for date in prices['date']]
prices['date'] = [date[0] for date in prices['date_split']]
prices['date'] = pd.to_datetime(prices['date'])

In [111]:
prices = prices.drop(['adjusted_close','date_split'], axis=1)

In [112]:
prices

,date,high,low,open,close,volume,dividend
ticker,,,,,,,
AAAU,2018-08-15,11.840000,11.740000,11.840000,11.740000,27300,NaN
ACWV,2016-01-26,66.790001,66.209999,66.209999,66.680000,124900,NaN
ACWV,2016-01-27,67.209999,66.180000,66.599998,66.500000,194100,NaN
ACWV,2016-01-28,67.070000,66.410004,67.070000,66.830002,360800,NaN
ACWV,2016-01-29,68.279999,67.309998,67.309998,68.239998,142200,NaN
ACWV,2016-02-01,68.709999,68.010002,68.029999,68.559998,84900,NaN
ACWV,2016-02-02,68.360001,67.769997,68.360001,67.989998,164100,NaN
ACWV,2016-02-03,68.660004,67.599998,68.540001,68.550003,199300,NaN
ACWV,2016-02-04,68.610001,68.110001,68.430000,68.360001,82900,NaN
ACWV,2016-02-05,68.199997,67.519997,68.199997,67.680000,95000,NaN
ACWV,2016-02-08,67.629997,66.889999,67.220001,67.510002,146100,NaN
ACWV,2016-02-09,67.610001,66.839996,66.839996,67.320000,314400,NaN
ACWV,2016-02-10,67.750000,67.199997,67.500000,67.290001,127600,NaN
ACWV,2016-02-11,67.019997,66.410004,66.550003,66.809998,224800,NaN
ACWV,2016-02-12,67.589996,66.860001,67.139999,67.559998,196700,NaN
ACWV,2016-02-16,68.400002,67.849998,68.400002,68.400002,248800,NaN
ACWV,2016-02-17,69.000000,68.389999,68.610001,68.940002,505900,NaN
ACWV,2016-02-18,69.160004,68.709999,68.970001,68.959999,192200,NaN
ACWV,2016-02-19,69.180000,68.760002,68.820000,69.139999,73200,NaN
ACWV,2016-02-22,69.900002,69.629997,69.769997,69.820000,238600,NaN
ACWV,2016-02-23,69.650002,69.250000,69.529999,69.339996,379100,NaN
ACWV,2016-02-24,69.709999,68.820000,68.959999,69.650002,222500,NaN
ACWV,2016-02-25,70.309998,69.730003,69.849998,70.309998,382400,NaN
ACWV,2016-02-26,70.550003,69.769997,70.550003,69.790001,511200,NaN
ACWV,2016-02-29,70.029999,69.379997,69.760002,69.379997,75500,NaN
ACWV,2016-03-01,70.489998,69.879997,69.900002,70.430000,315300,NaN
ACWV,2016-03-02,70.699997,70.120003,70.500000,70.699997,275200,NaN
ACWV,2016-03-03,70.690002,70.320000,70.620003,70.660004,444600,NaN
ACWV,2016-03-04,71.139999,70.599998,70.809998,70.989998,238100,NaN
ACWV,2016-03-07,71.029999,70.500000,70.690002,70.830002,274600,NaN
...,...,...,...,...,...,...,...
ZSL,2018-08-08,37.880001,37.380001,37.610001,37.560001,6500,NaN
ZSL,2018-08-09,37.470001,37.200001,37.310001,37.430000,2100,NaN
ZSL,2018-08-10,38.150002,37.560001,37.680000,38.110001,14200,NaN
ZSL,2018-08-13,39.779999,38.369999,38.369999,39.770000,42900,NaN
ZSL,2018-08-14,39.580002,39.130001,39.450001,39.320000,12300,NaN
ZSL,2018-08-15,42.980000,40.959999,40.959999,42.830002,29900,NaN
ZSL,2018-08-16,41.610001,40.599998,41.410000,41.560001,18500,NaN
ZSL,2018-08-17,41.610001,40.610001,41.220001,40.610001,19200,NaN
ZSL,2018-08-20,41.439999,40.840000,41.060001,40.959999,12000,NaN
ZSL,2018-08-21,41.139999,40.740002,40.820000,40.900002,16400,NaN
ZSL,2018-08-22,41.290001,40.820000,40.900002,40.959999,4600,NaN
ZSL,2018-08-23,42.439999,41.650002,41.840000,42.430000,22500,NaN
ZSL,2018-08-24,41.240002,40.340000,41.040001,40.630001,51200,NaN
ZSL,2018-08-27,40.480000,40.160000,40.470001,40.299999,5100,NaN
ZSL,2018-08-28,41.130001,40.080002,40.110001,41.130001,12100,NaN
ZSL,2018-08-29,41.200001,40.689999,40.910000,40.939999,11200,NaN
ZSL,2018-08-30,42.270000,41.799999,41.849998,42.049999,9000,NaN
ZSL,2018-08-31,42.500000,41.799999,41.840000,42.320000,8100,NaN
ZSL,2018-09-04,45.200001,44.349998,44.720001,44.349998,21800,NaN
ZSL,2018-09-05,44.320000,43.720001,43.900002,44.099998,11900,NaN
ZSL,2018-09-06,44.650002,43.639999,43.880001,44.400002,56600,NaN
ZSL,2018-09-07,44.570000,43.740002,44.380001,44.419998,10100,NaN
ZSL,2018-09-10,44.439999,44.020000,44.020000,44.349998,5800,NaN
ZSL,2018-09-11,45.750000,44.450001,45.090000,44.709999,16200,NaN
ZSL,2018-09-12,44.860001,43.700001,44.860001,43.779999,8600,NaN
ZSL,2018-09-13,44.320000,43.180000,43.389999,44.209999,19200,NaN
ZSL,2018-09-14,44.980000,44.180000,44.180000,44.970001,11500,NaN
ZSL,2018-09-17,44.369999,44.009998,44.099998,44.330002,9900,NaN
ZSL,2018-09-18,44.630001,44.040001,44.160000,44.459999,3200,NaN
ZSL,2018-09-19,44.130001,43.310001,44.119999,43.869999,33100,NaN

In [117]:
prices = prices.fillna(0.0)
prices['split'] = 1.0

In [121]:
tickers = prices.index

In [125]:
tickers = sorted(list(tickers))

In [126]:
prices = prices.sort_values(['ticker', 'date'])

In [127]:
prices

,date,high,low,open,close,volume,dividend,split
ticker,,,,,,,,
AAAU,2018-08-15,11.840000,11.740000,11.840000,11.740000,27300,0.000,1.0
AAAU,2018-08-16,11.800000,11.740000,11.780000,11.740000,428400,0.000,1.0
AAAU,2018-08-17,11.820000,11.770000,11.800000,11.820000,52400,0.000,1.0
AAAU,2018-08-20,11.910000,11.850000,11.880000,11.900000,28700,0.000,1.0
AAAU,2018-08-21,11.950000,11.890000,11.920000,11.930000,30600,0.000,1.0
AAAU,2018-08-22,11.980000,11.940000,11.980000,11.960000,101200,0.000,1.0
AAAU,2018-08-23,11.920000,11.850000,11.910000,11.850000,54800,0.000,1.0
AAAU,2018-08-24,12.080000,11.960000,11.970000,12.050000,106500,0.000,1.0
AAAU,2018-08-27,12.130000,12.060000,12.060000,12.100000,295100,0.000,1.0
AAAU,2018-08-28,12.130000,12.010000,12.130000,12.010000,30400,0.000,1.0
AAAU,2018-08-29,12.060000,12.030000,12.060000,12.050000,31800,0.000,1.0
AAAU,2018-08-30,12.030000,11.970000,12.030000,12.010000,804500,0.000,1.0
AAAU,2018-08-31,12.050000,11.990000,12.040000,12.000000,39500,0.000,1.0
AAAU,2018-09-04,11.940000,11.900000,11.910000,11.920000,6000,0.000,1.0
AAAU,2018-09-05,11.980000,11.960000,11.980000,11.970000,1032800,0.000,1.0
AAAU,2018-09-06,12.070000,11.980000,12.070000,12.000000,22900,0.000,1.0
AAAU,2018-09-07,11.980000,11.940000,11.970000,11.960000,20500,0.000,1.0
AAAU,2018-09-10,11.970000,11.940000,11.970000,11.950000,64300,0.000,1.0
AAAU,2018-09-11,11.960000,11.880000,11.900000,11.960000,6800,0.000,1.0
AAAU,2018-09-12,12.070000,12.020000,12.030000,12.070000,1600,0.000,1.0
AAAU,2018-09-13,12.120000,12.010000,12.120000,12.010000,5900,0.000,1.0
AAAU,2018-09-14,12.010000,11.930000,12.010000,11.930000,13700,0.000,1.0
AAAU,2018-09-17,12.040000,12.000000,12.010000,12.010000,2214000,0.000,1.0
AAAU,2018-09-18,12.030000,11.980000,12.030000,11.980000,1000,0.000,1.0
AAAU,2018-09-19,12.040000,12.030000,12.040000,12.030000,17400,0.000,1.0
AAAU,2018-09-20,12.070000,12.040000,12.060000,12.060000,8300,0.000,1.0
AAAU,2018-09-21,12.000000,11.970000,12.000000,11.990000,3000,1.323,1.0
AAAU,2018-09-24,12.030000,12.000000,12.010000,12.000000,31500,0.000,1.0
AAAU,2018-09-25,12.020000,12.010000,12.020000,12.010000,551600,0.000,1.0
AAAU,2018-09-26,11.990000,11.910000,11.960000,11.950000,166500,0.000,1.0
...,...,...,...,...,...,...,...,...
ZSL,2019-01-29,35.689999,35.430000,35.689999,35.630001,8400,0.000,1.0
ZSL,2019-01-30,35.480000,34.470001,35.259998,34.630001,251800,0.000,1.0
ZSL,2019-01-31,34.779999,34.049999,34.119999,34.660000,20300,0.000,1.0
ZSL,2019-02-01,35.320000,34.599998,34.689999,35.209999,150300,0.000,1.0
ZSL,2019-02-04,35.750000,35.320000,35.689999,35.439999,10300,0.000,1.0
ZSL,2019-02-05,35.669998,35.500000,35.520000,35.520000,6800,0.000,1.0
ZSL,2019-02-06,36.459999,35.700001,35.700001,36.380001,7100,0.000,1.0
ZSL,2019-02-07,36.419998,36.070000,36.419998,36.099998,16300,0.000,1.0
ZSL,2019-02-08,36.130001,35.680000,36.000000,35.700001,16900,0.000,1.0
ZSL,2019-02-11,36.419998,36.000000,36.230000,36.250000,8900,0.000,1.0
ZSL,2019-02-12,36.459999,36.189999,36.189999,36.290001,10200,0.000,1.0
ZSL,2019-02-13,37.080002,35.900002,36.279999,37.070000,9800,0.000,1.0
ZSL,2019-02-14,37.270000,36.730000,37.189999,36.820000,4700,0.000,1.0
ZSL,2019-02-15,36.799999,35.889999,36.490002,35.919998,30400,0.000,1.0
ZSL,2019-02-19,35.740002,34.930000,35.740002,34.980000,14200,0.000,1.0
ZSL,2019-02-20,34.799999,34.009998,34.650002,34.610001,13400,0.000,1.0
ZSL,2019-02-21,35.770000,35.189999,35.220001,35.770000,10200,0.000,1.0
ZSL,2019-02-22,35.430000,35.130001,35.400002,35.279999,15600,0.000,1.0
ZSL,2019-02-25,35.599998,35.160000,35.160000,35.450001,38700,0.000,1.0
ZSL,2019-02-26,35.759998,35.299999,35.480000,35.299999,8200,0.000,1.0
ZSL,2019-02-27,36.299999,35.709999,35.709999,36.209999,17500,0.000,1.0
ZSL,2019-02-28,36.930000,36.259998,36.259998,36.779999,26200,0.000,1.0
ZSL,2019-03-01,39.110001,37.360001,37.590000,39.110001,75300,0.000,1.0
ZSL,2019-03-04,39.470001,39.279999,39.299999,39.380001,14900,0.000,1.0
ZSL,2019-03-05,39.560001,39.110001,39.369999,39.150002,8300,0.000,1.0
ZSL,2019-03-06,39.549999,39.360001,39.410000,39.419998,4400,0.000,1.0
ZSL,2019-03-07,40.070000,39.610001,40.000000,39.779999,11900,0.000,1.0
ZSL,2019-03-08,38.549999,37.930000,38.410000,38.000000,22500,0.000,1.0
ZSL,2019-03-11,38.520000,38.200001,38.230000,38.240002,6200,0.000,1.0
ZSL,2019-03-12,37.840000,37.597198,37.610001,37.685001,6326,0.000,1.0

In [131]:
tickers_set = set(tickers)
tickers_list = list(tickers_set)
tickers = [str(ticker) for ticker in tickers_list]

In [134]:
tickers = sorted(tickers)

In [139]:
prices = prices.drop_duplicates()

In [141]:
len(prices)

2878317

In [145]:
prices = prices.reset_index()
prices = prices[['ticker','date','open','high','low','close','volume','dividend','split']]

In [147]:
prices = prices.set_index('ticker')

In [149]:
prices = prices.sort_values(['ticker','date'])

In [150]:
prices

,date,open,high,low,close,volume,dividend,split
ticker,,,,,,,,
AAAU,2018-08-15,11.840000,11.840000,11.740000,11.740000,27300,0.000,1.0
AAAU,2018-08-16,11.780000,11.800000,11.740000,11.740000,428400,0.000,1.0
AAAU,2018-08-17,11.800000,11.820000,11.770000,11.820000,52400,0.000,1.0
AAAU,2018-08-20,11.880000,11.910000,11.850000,11.900000,28700,0.000,1.0
AAAU,2018-08-21,11.920000,11.950000,11.890000,11.930000,30600,0.000,1.0
AAAU,2018-08-22,11.980000,11.980000,11.940000,11.960000,101200,0.000,1.0
AAAU,2018-08-23,11.910000,11.920000,11.850000,11.850000,54800,0.000,1.0
AAAU,2018-08-24,11.970000,12.080000,11.960000,12.050000,106500,0.000,1.0
AAAU,2018-08-27,12.060000,12.130000,12.060000,12.100000,295100,0.000,1.0
AAAU,2018-08-28,12.130000,12.130000,12.010000,12.010000,30400,0.000,1.0
AAAU,2018-08-29,12.060000,12.060000,12.030000,12.050000,31800,0.000,1.0
AAAU,2018-08-30,12.030000,12.030000,11.970000,12.010000,804500,0.000,1.0
AAAU,2018-08-31,12.040000,12.050000,11.990000,12.000000,39500,0.000,1.0
AAAU,2018-09-04,11.910000,11.940000,11.900000,11.920000,6000,0.000,1.0
AAAU,2018-09-05,11.980000,11.980000,11.960000,11.970000,1032800,0.000,1.0
AAAU,2018-09-06,12.070000,12.070000,11.980000,12.000000,22900,0.000,1.0
AAAU,2018-09-07,11.970000,11.980000,11.940000,11.960000,20500,0.000,1.0
AAAU,2018-09-10,11.970000,11.970000,11.940000,11.950000,64300,0.000,1.0
AAAU,2018-09-11,11.900000,11.960000,11.880000,11.960000,6800,0.000,1.0
AAAU,2018-09-12,12.030000,12.070000,12.020000,12.070000,1600,0.000,1.0
AAAU,2018-09-13,12.120000,12.120000,12.010000,12.010000,5900,0.000,1.0
AAAU,2018-09-14,12.010000,12.010000,11.930000,11.930000,13700,0.000,1.0
AAAU,2018-09-17,12.010000,12.040000,12.000000,12.010000,2214000,0.000,1.0
AAAU,2018-09-18,12.030000,12.030000,11.980000,11.980000,1000,0.000,1.0
AAAU,2018-09-19,12.040000,12.040000,12.030000,12.030000,17400,0.000,1.0
AAAU,2018-09-20,12.060000,12.070000,12.040000,12.060000,8300,0.000,1.0
AAAU,2018-09-21,12.000000,12.000000,11.970000,11.990000,3000,1.323,1.0
AAAU,2018-09-24,12.010000,12.030000,12.000000,12.000000,31500,0.000,1.0
AAAU,2018-09-25,12.020000,12.020000,12.010000,12.010000,551600,0.000,1.0
AAAU,2018-09-26,11.960000,11.990000,11.910000,11.950000,166500,0.000,1.0
...,...,...,...,...,...,...,...,...
ZSL,2019-01-29,35.689999,35.689999,35.430000,35.630001,8400,0.000,1.0
ZSL,2019-01-30,35.259998,35.480000,34.470001,34.630001,251800,0.000,1.0
ZSL,2019-01-31,34.119999,34.779999,34.049999,34.660000,20300,0.000,1.0
ZSL,2019-02-01,34.689999,35.320000,34.599998,35.209999,150300,0.000,1.0
ZSL,2019-02-04,35.689999,35.750000,35.320000,35.439999,10300,0.000,1.0
ZSL,2019-02-05,35.520000,35.669998,35.500000,35.520000,6800,0.000,1.0
ZSL,2019-02-06,35.700001,36.459999,35.700001,36.380001,7100,0.000,1.0
ZSL,2019-02-07,36.419998,36.419998,36.070000,36.099998,16300,0.000,1.0
ZSL,2019-02-08,36.000000,36.130001,35.680000,35.700001,16900,0.000,1.0
ZSL,2019-02-11,36.230000,36.419998,36.000000,36.250000,8900,0.000,1.0
ZSL,2019-02-12,36.189999,36.459999,36.189999,36.290001,10200,0.000,1.0
ZSL,2019-02-13,36.279999,37.080002,35.900002,37.070000,9800,0.000,1.0
ZSL,2019-02-14,37.189999,37.270000,36.730000,36.820000,4700,0.000,1.0
ZSL,2019-02-15,36.490002,36.799999,35.889999,35.919998,30400,0.000,1.0
ZSL,2019-02-19,35.740002,35.740002,34.930000,34.980000,14200,0.000,1.0
ZSL,2019-02-20,34.650002,34.799999,34.009998,34.610001,13400,0.000,1.0
ZSL,2019-02-21,35.220001,35.770000,35.189999,35.770000,10200,0.000,1.0
ZSL,2019-02-22,35.400002,35.430000,35.130001,35.279999,15600,0.000,1.0
ZSL,2019-02-25,35.160000,35.599998,35.160000,35.450001,38700,0.000,1.0
ZSL,2019-02-26,35.480000,35.759998,35.299999,35.299999,8200,0.000,1.0
ZSL,2019-02-27,35.709999,36.299999,35.709999,36.209999,17500,0.000,1.0
ZSL,2019-02-28,36.259998,36.930000,36.259998,36.779999,26200,0.000,1.0
ZSL,2019-03-01,37.590000,39.110001,37.360001,39.110001,75300,0.000,1.0
ZSL,2019-03-04,39.299999,39.470001,39.279999,39.380001,14900,0.000,1.0
ZSL,2019-03-05,39.369999,39.560001,39.110001,39.150002,8300,0.000,1.0
ZSL,2019-03-06,39.410000,39.549999,39.360001,39.419998,4400,0.000,1.0
ZSL,2019-03-07,40.000000,40.070000,39.610001,39.779999,11900,0.000,1.0
ZSL,2019-03-08,38.410000,38.549999,37.930000,38.000000,22500,0.000,1.0
ZSL,2019-03-11,38.230000,38.520000,38.200001,38.240002,6200,0.000,1.0
ZSL,2019-03-12,37.610001,37.840000,37.597198,37.685001,6326,0.000,1.0

In [151]:
for ticker in tickers:
    ticker_frame = prices[prices.index == ticker]
    ticker_frame.to_csv('/home/ubuntu/csvs/{}.csv'.format(ticker),index=False)