In [1]:
import pickle

import numpy as np
import pandas as pd

In [3]:
with open('buyspy.pickle', 'rb') as f:
    df = pickle.load(f)

In [6]:
prices = pd.read_csv('/home/ubuntu/csvdir/daily/AAXJ.csv')

In [18]:
prices

            date     open     high      low    close   volume  dividend  split
0     2014-03-17  51.7911  52.0718  51.7911  51.8998   299469   0.00000    1.0
1     2014-03-18  51.9903  52.3615  51.9722  52.2619   242366   0.00000    1.0
2     2014-03-19  52.0175  52.0446  51.1030  51.3565   387458   0.00000    1.0
3     2014-03-20  50.6412  51.1663  50.5778  51.1120   504789   0.00000    1.0
4     2014-03-21  51.5647  51.9812  51.3769  51.4742   452137   0.82461    1.0
5     2014-03-24  51.8454  52.0492  51.6734  51.9269   299868   0.00000    1.0
6     2014-03-25  52.2619  52.4973  52.1352  52.3344   437929   0.00000    1.0
7     2014-03-26  52.6875  52.7871  52.3615  52.3615   418676   0.00000    1.0
8     2014-03-27  52.3977  52.8686  52.3977  52.8052   551433   0.00000    1.0
9     2014-03-28  53.0587  53.6382  52.8595  53.3213   246235   0.00000    1.0
10    2014-03-31  53.7197  53.7740  53.4662  53.5024   282716   0.00000    1.0
11    2014-04-01  54.0185  54.1815  53.9438  54.1724   379710   0.00000    1.0
12    2014-04-02  54.1362  54.3354  54.1045  54.2720   539700   0.00000    1.0
13    2014-04-03  54.0366  54.1815  53.7287  54.1271   720924   0.00000    1.0
14    2014-04-04  54.5165  54.9579  53.9823  54.0094   322329   0.00000    1.0
15    2014-04-07  53.9551  54.2358  53.7559  53.9008   475021   0.00000    1.0
16    2014-04-08  54.6342  54.9601  54.5708  54.7066   301431   0.00000    1.0
17    2014-04-09  55.1412  55.4219  54.7247  55.2046   313661   0.00000    1.0
18    2014-04-10  55.4853  55.6121  54.9330  55.0507  1664407   0.00000    1.0
19    2014-04-11  54.6432  54.9964  54.6432  54.9330   394672   0.00000    1.0
20    2014-04-14  55.1141  55.2227  54.8515  55.0869   417331   0.00000    1.0
21    2014-04-15  54.7609  54.7881  53.9460  54.5527   376013   0.00000    1.0
22    2014-04-16  54.8334  55.0416  54.6432  54.9964   348337   0.00000    1.0
23    2014-04-17  54.9964  55.2951  54.9330  55.1141   149723   0.00000    1.0
24    2014-04-21  55.0145  55.0145  54.7520  54.8605   406971   0.00000    1.0
25    2014-04-22  54.8696  54.9964  54.6885  54.6885  1392876   0.00000    1.0
26    2014-04-23  54.4169  54.5436  54.1317  54.3444   650071   0.00000    1.0
27    2014-04-24  54.4621  54.4621  54.1000  54.4440   179983   0.00000    1.0
28    2014-04-25  53.8555  53.8555  53.5205  53.8193  1149185   0.00000    1.0
29    2014-04-28  53.7740  53.9823  53.5386  53.8736   366107   0.00000    1.0
...          ...      ...      ...      ...      ...      ...       ...    ...
1229  2019-02-01  68.5100  68.6300  68.3200  68.5000   707253   0.00000    1.0
1230  2019-02-04  68.4000  68.9350  68.3600  68.8100  1517541   0.00000    1.0
1231  2019-02-05  69.1000  69.8300  69.0550  69.7600   585359   0.00000    1.0
1232  2019-02-06  69.7800  69.7800  69.0300  69.1600   865248   0.00000    1.0
1233  2019-02-07  68.6300  68.9100  67.8900  68.4900   701670   0.00000    1.0
1234  2019-02-08  67.9700  68.3000  67.8000  68.2400   782575   0.00000    1.0
1235  2019-02-11  68.4900  68.5000  68.1700  68.1900   715071   0.00000    1.0
1236  2019-02-12  68.6500  68.8300  68.5500  68.7000  1184769   0.00000    1.0
1237  2019-02-13  69.0300  69.0600  68.4500  68.6000   560195   0.00000    1.0
1238  2019-02-14  68.3700  68.7950  68.1600  68.5900   753962   0.00000    1.0
1239  2019-02-15  68.3300  68.4100  68.0900  68.2600   527538   0.00000    1.0
1240  2019-02-19  68.1900  69.0200  68.1279  68.8500   778842   0.00000    1.0
1241  2019-02-20  69.3300  69.7700  69.2400  69.3800  1767172   0.00000    1.0
1242  2019-02-21  69.3700  69.4500  69.0300  69.2500  1464658   0.00000    1.0
1243  2019-02-22  69.8800  70.1500  69.7500  70.0200   741731   0.00000    1.0
1244  2019-02-25  70.7700  71.0600  70.7100  70.8200  1042307   0.00000    1.0
1245  2019-02-26  70.1800  70.6600  70.1300  70.4900  1560322   0.00000    1.0
1246  2019-02-27  70.0200  70.1800  69.7100  69.9200   968700   0.00000    1.0
1247  2019-02-28  69.5100  69.5100  69.0900  69.2500  3756142   0.00000    1.0
1248  2019-03-01  69.9000  69.9000  69.3100  69.4800   502537   0.00000    1.0
1249  2019-03-04  69.8900  69.9600  69.0700  69.6400  1490889   0.00000    1.0
1250  2019-03-05  69.9800  70.3900  69.8100  70.2800   966860   0.00000    1.0
1251  2019-03-06  70.2600  70.3900  69.9800  69.9800   663136   0.00000    1.0
1252  2019-03-07  69.5900  69.6000  68.6800  68.7800  1157728   0.00000    1.0
1253  2019-03-08  67.8200  68.2100  67.7100  68.1300  2818512   0.00000    1.0
1254  2019-03-11  68.7300  69.4300  68.7000  69.4000   666555   0.00000    1.0
1255  2019-03-12  69.7500  69.9100  69.5900  69.7900   654305   0.00000    1.0
1256  2019-03-13  69.7900  69.8700  69.6200  69.7000  1390665   0.00000    1.0
1257  2019-03-14  69.4600  69.4800  69.1550  69.3600   698126   0.00000    1.0
1258  2019-03-15  70.0600  70.3900  69.9800  70.3300   776589   0.00000    1.0

[1259 rows x 8 columns]

In [19]:
df.columns

Index(['SPY', 'algo_volatility', 'algorithm_period_return', 'alpha',
       'benchmark_period_return', 'benchmark_volatility', 'beta',
       'capital_used', 'ending_cash', 'ending_exposure', 'ending_value',
       'excess_return', 'gross_leverage', 'long_exposure', 'long_value',
       'longs_count', 'max_drawdown', 'max_leverage', 'net_leverage', 'orders',
       'period_close', 'period_label', 'period_open', 'pnl', 'portfolio_value',
       'positions', 'returns', 'sharpe', 'short_exposure', 'short_value',
       'shorts_count', 'sortino', 'starting_cash', 'starting_exposure',
       'starting_value', 'trading_days', 'transactions',
       'treasury_period_return'],
      dtype='object')

In [17]:
df.pnl

2014-03-17 20:00:00+00:00        0.000000
2014-03-18 20:00:00+00:00       -0.856075
2014-03-19 20:00:00+00:00       -9.861570
2014-03-20 20:00:00+00:00       18.743530
2014-03-21 20:00:00+00:00      -20.473200
2014-03-24 20:00:00+00:00      -28.769710
2014-03-25 20:00:00+00:00       38.996305
2014-03-26 20:00:00+00:00      -73.627630
2014-03-27 20:00:00+00:00      -25.625860
2014-03-28 20:00:00+00:00       65.150015
2014-03-31 20:00:00+00:00      122.983135
2014-04-01 20:00:00+00:00      111.437520
2014-04-02 20:00:00+00:00       61.944665
2014-04-03 20:00:00+00:00      -28.104200
2014-04-04 20:00:00+00:00     -263.324105
2014-04-07 20:00:00+00:00     -262.084775
2014-04-08 20:00:00+00:00      102.351785
2014-04-09 20:00:00+00:00      287.622770
2014-04-10 20:00:00+00:00     -606.719410
2014-04-11 20:00:00+00:00     -269.031960
2014-04-14 20:00:00+00:00      245.211565
2014-04-15 20:00:00+00:00      227.355860
2014-04-16 20:00:00+00:00      365.387140
2014-04-17 20:00:00+00:00       51.945940
2014-04-21 20:00:00+00:00      134.383000
2014-04-22 20:00:00+00:00      183.939150
2014-04-23 20:00:00+00:00     -100.358860
2014-04-24 20:00:00+00:00       88.579420
2014-04-25 20:00:00+00:00     -377.503605
2014-04-28 20:00:00+00:00      147.543745
                                 ...
2019-02-01 21:00:00+00:00     1582.765625
2019-02-04 21:00:00+00:00    23251.316165
2019-02-05 21:00:00+00:00    13959.130490
2019-02-06 21:00:00+00:00    -4420.657715
2019-02-07 21:00:00+00:00   -31885.514775
2019-02-08 21:00:00+00:00     4042.883585
2019-02-11 21:00:00+00:00     1849.642835
2019-02-12 21:00:00+00:00    42779.025515
2019-02-13 21:00:00+00:00    10949.581085
2019-02-14 21:00:00+00:00    -7509.965880
2019-02-15 21:00:00+00:00    36853.869235
2019-02-19 21:00:00+00:00     5921.026845
2019-02-20 21:00:00+00:00     6905.404060
2019-02-21 21:00:00+00:00   -12225.241015
2019-02-22 21:00:00+00:00    21261.640425
2019-02-25 21:00:00+00:00     4709.568530
2019-02-26 21:00:00+00:00    -2489.400470
2019-02-27 21:00:00+00:00    -1482.949875
2019-02-28 21:00:00+00:00    -6455.677285
2019-03-01 21:00:00+00:00    21609.104050
2019-03-04 21:00:00+00:00   -12681.080870
2019-03-05 21:00:00+00:00    -4722.618980
2019-03-06 21:00:00+00:00   -21038.890565
2019-03-07 21:00:00+00:00   -28899.479015
2019-03-08 21:00:00+00:00    -6849.816280
2019-03-11 20:00:00+00:00    49642.463910
2019-03-12 20:00:00+00:00    13115.438680
2019-03-13 20:00:00+00:00    23115.689470
2019-03-14 20:00:00+00:00    -2262.209630
2019-03-15 20:00:00+00:00    17395.463450
Name: pnl, Length: 1259, dtype: float64