In [1]:
import numpy as np
import pandas as pd

import pickle
import requests

import yahoofinancials

import pandas_datareader.data as pdr
import fix_yahoo_finance as yf

import prices

from fake_useragent import UserAgent

In [2]:
ua = UserAgent()
user_agent = {'User-agent': ua.random}

In [3]:
yf.pdr_override()

In [4]:
with open('tickers.pkl', 'rb') as f:
    tickers = pickle.load(f)

In [5]:
len(tickers)

2007

In [6]:
pdr.get_data_yahoo(tickers[0], actions=True)

[*********************100%***********************]  1 of 1 downloaded

ValueError: zero-size array to reduction operation maximum which has no identity

In [7]:
df = prices.get_yahoo_prices_all_tickers(tickers)

[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  1 of 1 downloaded

KeyboardInterrupt:

In [10]:
prices.get_yahoo_prices_one_ticker(tickers[16])

[*********************100%***********************]  1 of 1 downloaded

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Ticker
Date,,,,,,,,,
2008-11-19,47.790001,50.799999,40.709999,41.000000,35.125454,560900,0.000,1.0,ERX
2008-11-20,39.980000,39.980000,26.629999,27.100000,23.217070,854700,0.000,1.0,ERX
2008-11-21,29.889999,36.730000,28.000000,36.230000,31.038902,1125200,0.000,1.0,ERX
2008-11-24,40.099998,45.880001,36.419998,42.290001,36.230621,1108000,0.000,1.0,ERX
2008-11-25,44.290001,46.160000,40.720001,44.000000,37.695610,601800,0.000,1.0,ERX
2008-11-26,42.750000,51.990002,42.000000,51.900002,44.463688,676800,0.000,1.0,ERX
2008-11-28,49.500000,49.860001,46.439999,49.360001,42.287621,181900,0.000,1.0,ERX
2008-12-01,43.160000,44.590000,34.110001,34.500000,29.556784,702700,0.000,1.0,ERX
2008-12-02,36.619999,38.090000,34.000000,37.660000,32.264015,959100,0.000,1.0,ERX
2008-12-03,34.270000,38.810001,33.660000,38.680000,33.137863,1320800,0.000,1.0,ERX
2008-12-04,36.480000,37.900002,29.090000,31.090000,26.635378,1339000,0.000,1.0,ERX
2008-12-05,28.959999,32.689999,25.600000,32.500000,27.843353,2187100,0.000,1.0,ERX
2008-12-08,36.400002,38.580002,35.340000,36.759998,31.492973,1986700,0.000,1.0,ERX
2008-12-09,35.599998,40.080002,35.119999,36.919998,31.630045,1608000,0.000,1.0,ERX
2008-12-10,39.669998,43.320000,38.779999,42.599998,36.496204,2168900,0.000,1.0,ERX
2008-12-11,43.610001,46.980000,40.360001,42.090000,36.059280,2021500,0.000,1.0,ERX
2008-12-12,38.400002,42.130001,36.750000,40.689999,34.859867,1399200,0.000,1.0,ERX
2008-12-15,44.110001,44.400002,38.169998,40.730000,34.894142,1746300,0.000,1.0,ERX
2008-12-16,42.610001,45.000000,40.840000,44.279999,37.935493,1162100,0.000,1.0,ERX
2008-12-17,44.220001,46.430000,42.360001,42.930000,36.785568,1313700,0.008,1.0,ERX
2008-12-18,43.080002,43.080002,34.330002,35.200001,30.161938,1508700,0.000,1.0,ERX
2008-12-19,36.090000,38.349998,34.779999,35.189999,30.153370,1172900,0.000,1.0,ERX
2008-12-22,36.009998,36.380001,30.620001,32.720001,28.036892,1164400,0.000,1.0,ERX
2008-12-23,33.090000,33.990002,31.299999,31.900000,27.334257,979500,0.000,1.0,ERX
2008-12-24,31.500000,32.590000,31.040001,32.189999,27.582750,274900,0.000,1.0,ERX
2008-12-26,33.060001,34.310001,32.360001,33.849998,29.005156,673500,0.000,1.0,ERX
2008-12-29,35.750000,36.200001,34.200001,35.599998,30.504688,964400,0.000,1.0,ERX
2008-12-30,35.590000,38.000000,34.830002,37.830002,32.415516,772600,0.000,1.0,ERX
2008-12-31,37.570000,40.520000,36.970001,38.980000,33.400921,1008200,0.000,1.0,ERX
2009-01-02,39.500000,45.500000,39.500000,44.730000,38.327938,1496600,0.000,1.0,ERX
...,...,...,...,...,...,...,...,...,...
2019-01-25,19.440001,20.090000,19.400000,19.750000,19.750000,3593600,0.000,1.0,ERX
2019-01-28,18.930000,19.150000,18.500000,19.139999,19.139999,3763000,0.000,1.0,ERX
2019-01-29,19.469999,19.690001,19.260000,19.320000,19.320000,2792800,0.000,1.0,ERX
2019-01-30,19.719999,20.299999,19.360001,20.110001,20.110001,3377100,0.000,1.0,ERX
2019-01-31,20.230000,20.780001,20.040001,20.469999,20.469999,4537100,0.000,1.0,ERX
2019-02-01,21.299999,21.920000,20.959999,21.549999,21.549999,5491100,0.000,1.0,ERX
2019-02-04,21.190001,21.740000,20.650000,21.719999,21.719999,3485300,0.000,1.0,ERX
2019-02-05,21.629999,21.930000,21.459999,21.799999,21.799999,3648400,0.000,1.0,ERX
2019-02-06,21.530001,21.670000,21.270000,21.309999,21.309999,2996200,0.000,1.0,ERX
2019-02-07,20.900000,21.139999,19.320000,19.920000,19.920000,4498400,0.000,1.0,ERX
2019-02-08,19.760000,19.870001,18.600000,19.620001,19.620001,2875700,0.000,1.0,ERX
2019-02-11,19.219999,19.990000,19.160000,19.900000,19.900000,2875000,0.000,1.0,ERX
2019-02-12,20.709999,20.990000,20.370001,20.620001,20.620001,2679000,0.000,1.0,ERX
2019-02-13,20.889999,21.920000,20.830000,21.440001,21.440001,4985100,0.000,1.0,ERX
2019-02-14,21.219999,22.110001,21.090000,21.639999,21.639999,5014600,0.000,1.0,ERX
2019-02-15,22.230000,22.730000,22.160000,22.660000,22.660000,4076300,0.000,1.0,ERX
2019-02-19,22.360001,23.139999,22.250000,22.889999,22.889999,3174200,0.000,1.0,ERX
2019-02-20,22.760000,23.510000,22.750000,23.170000,23.170000,2176500,0.000,1.0,ERX
2019-02-21,22.969999,23.129999,21.850000,22.080000,22.080000,3955800,0.000,1.0,ERX
2019-02-22,22.540001,22.780001,21.940001,22.270000,22.270000,3042000,0.000,1.0,ERX
2019-02-25,21.969999,22.600000,21.969999,22.370001,22.370001,2284800,0.000,1.0,ERX
2019-02-26,22.309999,22.770000,22.139999,22.160000,22.160000,2345100,0.000,1.0,ERX
2019-02-27,22.530001,23.100000,22.100000,22.410000,22.410000,2707800,0.000,1.0,ERX
2019-02-28,22.400000,22.480000,21.330000,21.730000,21.730000,2724600,0.000,1.0,ERX
2019-03-01,22.090000,22.920000,22.090000,22.910000,22.910000,3646600,0.000,1.0,ERX
2019-03-04,23.200001,23.340000,22.000000,23.030001,23.030001,3989500,0.000,1.0,ERX
2019-03-05,23.170000,23.170000,22.330000,22.820000,22.820000,2429900,0.000,1.0,ERX
2019-03-06,22.320000,22.370001,21.600000,21.930000,21.930000,2874200,0.000,1.0,ERX
2019-03-07,21.950001,22.000000,21.290001,21.530001,21.530001,3092600,0.000,1.0,ERX
2019-03-08,20.490000,20.570000,19.740000,20.299999,20.299999,3163240,0.000,1.0,ERX

In [ ]:
spy = yahoofinancials.YahooFinancials('SPY')

In [ ]:
start = datetime.datetime(2016, 1, 1)
end = datetime.datetime(2019, 1, 1)

In [ ]:
pdr.get_data_yahoo('SPY', start, end, actions=True)

In [ ]:
pdr.get_data_yahoo_actions('SPY', start, end)